 language: node_js
 node_js:
   - "iojs"
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh"
  - "echo Hello"
env:
  - LAIKA_OPTIONS="-t 5000"